### ISSUE TITLE
Integrate real local STT, dialogue LLM, and Qwen3-TTS workers

### ISSUE THREAD

**Issue by hamedzurat** [hamedzurat/North-Neeladesh-Ministry-of-Communications#49]
## Parent

Parent issue: #40 — Build the complete authored exchange loop vertical slice

## Problem

Issue #44 implemented the voice-session orchestration and provider command contracts, but it does not implement the actual local voice providers. The default path uses checked-in smoke scripts that return a fixed transcript, fixed dialogue, and silent audio. The four worker commands must be replaced or supplemented with real offline workers so the voice session proves microphone capture, STT, dialogue inference, and Qwen3-TTS 1.7B synthesis.

## What to build

Implement the real local worker path behind the interfaces introduced by #44:

- microphone capture that records a bounded 16 kHz mono PCM utterance from the configured local input device;
- local STT using the selected whisper.cpp `base.en` configuration or an explicitly documented equivalent already accepted by the project;
- local dialogue generation using the accepted Qwen3-4B-Instruct-2507 Q4_K_M configuration through the bounded Subscriber Response Context contract;
- local TTS using Qwen3-TTS 1.7B only, with the Subscriber voice configuration required by the demo; and
- a documented offline launch path that points at pre-existing local model assets without downloading anything at runtime.

Keep #44's daemon and backend boundary. This issue is about real provider implementations and their integration, not a second voice protocol or a new authority path.

## Acceptance criteria

- [ ] The default documented real-worker path does not use a smoke script, hardcoded transcript, hardcoded dialogue, or generated silence.
- [ ] A real microphone capture produces bounded signed 16-bit mono PCM at 16 kHz and stops on PTT release or cancellation.
- [ ] STT transcribes a supplied PCM fixture and a real microphone utterance locally with no network request.
- [ ] The dialogue worker invokes the accepted local Qwen3-4B-Instruct-2507 Q4_K_M model and returns bounded Subscriber-specific dialogue from the supplied Response Context.
- [ ] The dialogue worker does not receive inaccessible state and cannot directly emit a Story Event, Routing, or other authoritative mutation.
- [ ] Qwen3-TTS 1.7B synthesizes the response at the contract sample rate and uses the requested Subscriber voice configuration.
- [ ] Pocket TTS, Piper, cloud APIs, and automatic TTS fallback engines are not used by the MVP path.
- [ ] STT, dialogue, and TTS processes have bounded timeouts, cancellation behavior, non-zero exit handling, invalid-output handling, and diagnostics that preserve authoritative state.
- [ ] A stale or failed worker result cannot create a Routing or Story Event, and voice failure remains visible to the frontend/backend.
- [ ] The real providers work through the existing Odin/backend/voice-daemon path and the same logical voice contract remains usable for Raspberry Pi deployment.
- [ ] Model paths, runtime dependencies, device selection, resource expectations, offline preflight, and required environment/configuration are documented. Model files and private reference audio remain outside the repository.
- [ ] Provider tests use deterministic fixtures or fakes for orchestration, bounds, cancellation, failure, and stale-result behavior; they do not require model files in CI.
- [ ] Manual acceptance on the target laptop confirms: hold PTT, speak, release PTT, observe a non-fixed transcript, observe a Subscriber-specific response, hear synthesized Qwen3-TTS 1.7B audio, and observe the complete voice status sequence.

## Blocked by

- #44 — Run one local voice Operator Session

## Not in scope

- Story Graph progression, Routing authority, Tap Bridge mechanics, or the four-Shift demo integration.
- Continuous LLM simulation of off-screen Subscribers.
- Automatic VAD, true full duplex, acoustic echo cancellation, or production worker supervision.
- Adding Pocket TTS or another fallback engine.

## Why this ticket exists

#44's smoke-provider plumbing is a useful prerequisite, but it does not satisfy the real-model requirements in #40 or #48. Do not close this ticket based only on adapter tests or smoke-worker output.

**Comment by hamedzurat** [comment]
Completed in commit db8bc950fe5199d8eb3f9a4dd36f2d63431d1306 (feat: improve offline voice runtime).

Implemented the real offline voice path:
- Local cpal microphone capture and playback with bounded signed 16-bit PCM handling.
- Local Whisper STT, Qwen3-4B dialogue, and Qwen3-TTS 1.7B workers.
- Persistent sentence-framed TTS streaming with native PyTorch SDPA attention.
- Multi-turn sessions, cancellation, bounded worker execution, diagnostics, and voice status logging.
- Voice selection propagated through the protocol, with random speakers enabled by default and deterministic override support.
- Offline model preflight/setup documentation and Ruff formatting configuration.

Validation completed:
- cargo test --workspace
- cargo fmt --all --check
- Ruff format check
- Python compilation
- uv lock --check
- Manual local GPU TTS, dialogue, and voice-session checks

The Raspberry Pi network audio-edge transport remains future work and is not required for this issue.
